### ISSUE TITLE
Stand-alone example script (post) error

### ISSUE THREAD

**Issue by cjstehno** [http-builder-ng/http-builder-ng#103]
Another stand-alone script issue...

```groovy
@Grab('io.github.http-builder-ng:http-builder-ng-core:0.14.1')

import static groovyx.net.http.HttpBuilder.configure
import static groovyx.net.http.ContentTypes.JSON
import groovyx.net.http.*

@groovy.transform.Canonical
class ItemScore {
    String item
    Long score
}

ItemScore itemScore = configure {
    request.uri = 'http://httpbin.org'
    request.contentType = JSON[0]
    response.parser(JSON[0]) { config, resp ->
        new ItemScore(NativeHandlers.Parsers.json(config, resp).json)
    }
}.post(ItemScore) {
    request.uri.path = '/post'
    request.body = new ItemScore('ASDFASEACV235', 90786)
}

println "Your score for item (${itemScore.item}) was (${itemScore.score})."
```

Results in an error:

```
java.lang.IllegalAccessError: tried to access class groovyx.net.http.JavaHttpBuilder$Action$JavaToServer from class groovyx.net.http.JavaHttpBuilder$Action
	at groovyx.net.http.JavaHttpBuilder$Action.lambda$execute$0(JavaHttpBuilder.java:116)
	at groovyx.net.http.JavaHttpBuilder$ThreadLocalAuth.with(JavaHttpBuilder.java:264)
	at groovyx.net.http.JavaHttpBuilder$Action.execute(JavaHttpBuilder.java:101)
	at groovyx.net.http.JavaHttpBuilder.doPost(JavaHttpBuilder.java:303)
	at groovyx.net.http.HttpObjectConfigImpl.nullInterceptor(HttpObjectConfigImpl.java:44)
	at groovyx.net.http.HttpBuilder.post(HttpBuilder.java:726)
	at groovyx.net.http.HttpBuilder$post$2.call(Unknown Source)
	at ConsoleScript32.run(ConsoleScript32:13)
```

I may have a fix for this one, but I cannot really check it until I have it deployed (without jumping through a lot of repo hoops). I changed the `JavaToServer` class from `private` to `protected` which I think will do the trick.

**Comment by cjstehno** [comment]
I have verified that this has been fixed in the `development` branch and will be in the next release.
