### ISSUE TITLE
Json post with Apache Http Client failed with length required error

### ISSUE THREAD

**Issue by luojunqiang** [http-builder-ng/http-builder-ng#177]
```
ItemScore itemScore = HttpBuilder.configure({ c -> new ApacheHttpBuilder(c); } as java.util.function.Function) {
    request.uri = 'http://httpbin.org'
    request.contentType = JSON[0]
    response.parser(JSON[0]) { config, resp ->
        new ItemScore(NativeHandlers.Parsers.json(config, resp).json)
    }
}.post(ItemScore) {
    request.uri.path = '/post'
    request.body = new ItemScore('ASDFASEACV235', 90786)
}

println "Your score for item (${itemScore.item}) was (${itemScore.score})."
```
with above code using ApacheHttpBuilder, cause error below:

```
Caught: groovyx.net.http.HttpException: Length Required
groovyx.net.http.HttpException: Length Required
        at groovyx.net.http.NativeHandlers.failure(NativeHandlers.java:69)
        at groovyx.net.http.HttpBuilder$ResponseHandlerFunction.apply(HttpBuilder.java:2305)
```

**Comment by cjstehno** [comment]
What version of HttpBuilder-NG are you using?

**Comment by cjstehno** [comment]
Looks like we must already be providing the Content-Length in the Java core client but not in the other two. I have a fix for this pending.
