### ISSUE TITLE
query with params without value fail

### ISSUE THREAD

**Issue by stlhrt** [http-builder-ng/http-builder-ng#184]
```
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.AbstractStringBuilder.substring(AbstractStringBuilder.java:935)
	at java.lang.StringBuilder.substring(StringBuilder.java:76)
	at groovyx.net.http.Form.decode(Form.java:81)
	at groovyx.net.http.UriBuilder.populateFrom(UriBuilder.java:265)
	at groovyx.net.http.UriBuilder.setFull(UriBuilder.java:316)
	at groovyx.net.http.HttpConfigs$BaseRequest.setUri(HttpConfigs.java:157)
```

when useRawValues = false
or 
```
Caused by: java.lang.ArrayIndexOutOfBoundsException: 1
	at groovyx.net.http.UriBuilder.lambda$extractQueryMap$2(UriBuilder.java:286)
	at java.util.HashMap.computeIfAbsent(HashMap.java:1126)
	at groovyx.net.http.UriBuilder.extractQueryMap(UriBuilder.java:284)
	at groovyx.net.http.UriBuilder.populateFrom(UriBuilder.java:263)
	at groovyx.net.http.UriBuilder.setFull(UriBuilder.java:316)
	at groovyx.net.http.HttpConfigs$BaseRequest.setUri(HttpConfigs.java:157)
```

**Comment by cjstehno** [comment]
Please provide a failing test case or example of the code.

**Comment by stlhrt** [comment]
```
@Grab('io.github.http-builder-ng:http-builder-ng-apache:1.0.2')

import groovyx.net.http.HttpBuilder

def httpBin = HttpBuilder.configure {
}

httpBin.get {
    request.uri = 'http://httpbin.org/?test'
}
```

**Comment by cjstehno** [comment]
Thanks for providing the fix for this. I will try to drop a release today.
