### ISSUE TITLE
Null header value results in java.net.SocketException: Connection reset

### ISSUE THREAD

**Issue by spartanhooah** [http-builder-ng/http-builder-ng#217]
With version 1.0.3, setting a header to a null value results in "java.net.SocketException: Connection reset". I've tried to create a simple example that reproduces the problem but I have been unsuccessful. However, here is an example that is failing:

```
static myServiceClient = configure {
    request.uri = SERVICE_HOST
    request.contentType = JSON
    request.uri.path = '/v1/path/to/service'
}

static postToMyService(idClaim, body) {
    myServiceClient.post {
        request.headers['test-header'] = null
        request.body = body
    }
}
```

The full stack trace is
```Caused by: java.lang.RuntimeException: java.net.SocketException: Connection reset
	at groovyx.net.http.NativeHandlers.exception(NativeHandlers.java:80)
	at groovyx.net.http.HttpBuilder.handleException(HttpBuilder.java:2292)
	at groovyx.net.http.JavaHttpBuilder.createAndExecute(JavaHttpBuilder.java:376)
	at groovyx.net.http.JavaHttpBuilder.doPost(JavaHttpBuilder.java:389)
	at groovyx.net.http.HttpObjectConfigImpl.nullInterceptor(HttpObjectConfigImpl.java:47)
	at groovyx.net.http.HttpBuilder.post(HttpBuilder.java:732)
	at groovyx.net.http.HttpBuilder.post(HttpBuilder.java:1391)
	at com.my.company.SomeTestClass.postSomething(SomeTestClass.groovy:19)
	... 1 more
Caused by: java.net.SocketException: Connection reset
	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1950)
	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1945)
	at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1944)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1514)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:352)
	at groovyx.net.http.JavaHttpBuilder$Action$JavaFromServer.<init>(JavaHttpBuilder.java:212)
	at groovyx.net.http.JavaHttpBuilder$Action.lambda$execute$2(JavaHttpBuilder.java:158)
	at groovyx.net.http.JavaHttpBuilder$ThreadLocalAuth.with(JavaHttpBuilder.java:331)
	at groovyx.net.http.JavaHttpBuilder$Action.execute(JavaHttpBuilder.java:122)
	at groovyx.net.http.JavaHttpBuilder.createAndExecute(JavaHttpBuilder.java:374)
	... 6 more
Caused by: java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(SocketInputStream.java:210)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
	at sun.security.ssl.InputRecord.read(InputRecord.java:503)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:975)
	at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:933)
	at sun.security.ssl.AppInputStream.read(AppInputStream.java:105)
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
	at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:735)
	at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:678)
	at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:706)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1593)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498)
	at sun.net.www.protocol.http.HttpURLConnection.getHeaderFieldKey(HttpURLConnection.java:3110)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getHeaderFieldKey(HttpsURLConnectionImpl.java:321)
	at groovyx.net.http.JavaHttpBuilder$Action$JavaFromServer.populateHeaders(JavaHttpBuilder.java:277)
	at groovyx.net.http.JavaHttpBuilder$Action$JavaFromServer.<init>(JavaHttpBuilder.java:210)
	... 10 more```

**Comment by cjstehno** [comment]
Is there a reason you need a `null` header or should it just be removed (by calling `headers.remove('test-header')`)?

If you feel that this is a real bug, please provide a use case along with a failing test case so that it may be reproduced, preferably using [Ersatz](http://stehno.com/ersatz/).

**Comment by spartanhooah** [comment]
A sister team at my work had one integration test that passed a null authentication token (on purpose). We were all quite puzzled as to what was going on until we tried an empty string instead, which worked fine. I don't know the HTTP spec well enough to know if null header values should be allowed, but I was able to make the call fine with Postman with what seemed like a null value (although it may have been creating an empty string under the hood).

In any case, my minimum example follows.

build.gradle
```
plugins {
    id 'groovy'
}

group 'spartanhooah'
version '1.0-SNAPSHOT'

repositories {
    mavenCentral()
    jcenter()
}

configurations.all {
    resolutionStrategy {
        force 'org.codehaus.groovy:groovy-all:2.4.9'
    }
}

dependencies {
    compile 'org.codehaus.groovy:groovy-all:2.3.11'
    compile 'io.github.http-builder-ng:http-builder-ng-core:1.0.3'

    testImplementation 'space.jasan:groovy-closure-support:0.4.0'
    testCompile 'com.stehno.ersatz:ersatz:1.9.0'
    testCompile 'io.github.http-builder-ng:http-builder-ng-core:1.0.3'
    testCompile 'org.spockframework:spock-core:1.1-groovy-2.4'
}
```

Failing test
```
import com.stehno.ersatz.ErsatzServer
import spock.lang.Specification

import static groovyx.net.http.HttpBuilder.configure

class HeaderTest extends Specification {
    def client = configure {
        request.uri = 'http://localhost:8080'
        request.uri.path = '/header/test'
        request.headers['test-header'] = null
    }

    def 'null header test'() {
        setup:
        ErsatzServer server = new ErsatzServer()

        server.expectations {
            get('/header/test') {
                called 1
                responder {
                    content 'Hello Ersatz', 'text/plain'
                }
            }
        }

        when:
        def result = client.get()

        then:
        result == 'Hello Ersatz'
    }
}
```

**Comment by spartanhooah** [comment]
Wait, no, it appears I don't understand how to call the Ersatz server with HTTP builder. With my example even commenting out the headers line still fails. The Ersatz documentation never gives a host, so what am I supposed to put for `request.uri`? If I don't put anything, your library complains (understandably) that the URI is not absolute. I tried using `server.getUrl` instead of localhost but that resulted in `java.lang.IllegalArgumentException: protocol = http host = null`. What am I not understanding here?

**Comment by cjstehno** [comment]
See the tests in HttpBuilderNG source code for examples, but you need to pass the Ersatz url into the builder config rather than localhost:8080. Ersatz creates a random port for each test.

**Comment by spartanhooah** [comment]
I'm still having trouble hitting the Ersatz server. My test class now looks like this:
```
import com.stehno.ersatz.ErsatzServer
import spock.lang.AutoCleanup
import spock.lang.Specification

import static groovyx.net.http.HttpBuilder.configure

class HeaderTest extends Specification {
    @AutoCleanup('stop')
    ErsatzServer server = new ErsatzServer()

    def 'null header test'() {
        println '################################ ' + server.httpUrl
        setup:
        def client = configure {
            request.uri = server.httpUrl
            request.uri.path = '/header/test'
            request.headers['test-header'] = null
        }

        server.expectations {
            get('/header/test') {
                called 1
                responder {
                    content 'Hello Ersatz', 'text/plain'
                }
            }
        }

        when:
        def result = client.get()

        then:
        result == 'Hello Ersatz'
    }
}
```

The print prints out a host of `http://localhost:-1` which seems strange, and the stack trace I get is
```
protocol = http host = null
java.lang.IllegalArgumentException: protocol = http host = null
	at sun.net.spi.DefaultProxySelector.select(DefaultProxySelector.java:177)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1150)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1050)
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:984)
	at groovyx.net.http.JavaHttpBuilder$Action.lambda$execute$2(JavaHttpBuilder.java:147)
	at groovyx.net.http.JavaHttpBuilder$ThreadLocalAuth.with(JavaHttpBuilder.java:331)
	at groovyx.net.http.JavaHttpBuilder$Action.execute(JavaHttpBuilder.java:122)
	at groovyx.net.http.JavaHttpBuilder.createAndExecute(JavaHttpBuilder.java:374)
	at groovyx.net.http.JavaHttpBuilder.doGet(JavaHttpBuilder.java:381)
	at groovyx.net.http.HttpObjectConfigImpl.nullInterceptor(HttpObjectConfigImpl.java:47)
	at groovyx.net.http.HttpBuilder.get(HttpBuilder.java:346)
	at groovyx.net.http.HttpBuilder.get(HttpBuilder.java:1297)
	at groovyx.net.http.HttpBuilder.get(HttpBuilder.java:322)
	at HeaderTest.null header test(HeaderTest.groovy:30)
```

**Comment by cjstehno** [comment]
You are configuring the client before the server so there is no port defined.
Put the client config block after the server config block and this should work.

**Comment by spartanhooah** [comment]
Oh, of course. The problem now is that I can't get this toy example to fail! I also discovered that if I run one of our services locally (in Docker), I don't get the socket exception. Only if I run the test against an instance of the service running in OpenShift (RedHat's extension of Kubernetes) do I get the exception. So I guess it's something to do with either OpenShift, Kubernetes, or my company's network.
