### ISSUE TITLE
Unable to experiment within the groovy console

### ISSUE THREAD

**Issue by neuromantik33** [http-builder-ng/http-builder-ng#220]
Hi,

I've developed the Google Java client for httpbuilder-ng and while everything seems to work fine in scripts for some reason within the groovy console I'm getting the following exception:

```
groovy.lang.GroovyRuntimeException: Ambiguous method overloading for method groovyx.net.http.JavaHttpBuilder#configure.
Cannot resolve which method to invoke for [class ideaGroovyConsole$_run_closure1] due to overlapping prototypes between:
	[interface java.util.function.Consumer]
	[interface java.util.function.Function]
	at groovy.lang.MetaClassImpl.doChooseMostSpecificParams(MetaClassImpl.java:3279)
	at groovy.lang.MetaClassImpl.chooseMostSpecificParams(MetaClassImpl.java:3256)
	at groovy.lang.MetaClassImpl.chooseMethodInternal(MetaClassImpl.java:3245)
	at groovy.lang.MetaClassImpl.chooseMethod(MetaClassImpl.java:3188)
	at groovy.lang.MetaClassImpl.pickStaticMethod(MetaClassImpl.java:1535)
	at groovy.lang.MetaClassImpl.retrieveStaticMethod(MetaClassImpl.java:1431)
	at groovy.lang.MetaClassImpl.createStaticSite(MetaClassImpl.java:3447)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.createCallStaticSite(CallSiteArray.java:76)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.createCallSite(CallSiteArray.java:161)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:115)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:127)
	at ideaGroovyConsole.run(ideaGroovyConsole.groovy:3)
	at groovy.lang.GroovyShell.runScriptOrMainOrTestOrRunnable(GroovyShell.java:266)
	at groovy.lang.GroovyShell.run(GroovyShell.java:376)
	at groovy.lang.GroovyShell.run(GroovyShell.java:355)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSite.invoke(PogoMetaMethodSite.java:167)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.call(PogoMetaMethodSite.java:70)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:135)
	at console.run(console.groovy:11)
	at groovy.ui.GroovyMain.processReader(GroovyMain.java:571)
	at groovy.ui.GroovyMain.processFiles(GroovyMain.java:490)
	at groovy.ui.GroovyMain.run(GroovyMain.java:334)
	at groovy.ui.GroovyMain.access$1400(GroovyMain.java:69)
	at groovy.ui.GroovyMain$GroovyCommand.process(GroovyMain.java:295)
	at groovy.ui.GroovyMain.processArgs(GroovyMain.java:134)
	at groovy.ui.GroovyMain.main(GroovyMain.java:116)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.tools.GroovyStarter.rootLoader(GroovyStarter.java:110)
	at org.codehaus.groovy.tools.GroovyStarter.main(GroovyStarter.java:128)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.CommandLineWrapper.main(CommandLineWrapper.java:66)
```

My code is pretty simple consisting of 
```groovy
import groovyx.net.http.JavaHttpBuilder

def http = JavaHttpBuilder.configure {
    request.uri = 'https://ifconfig.co/json'
    request.contentType = 'application/json'
    request.headers = ['User-Agent': 'curl/7.58.0']
}

def body = http.get()
println "body = $body"
```

When I run it within a script it works however. Any ideas?

**Comment by grv87** [comment]
For me, casting to `Consumer` fixed the problem. Like this:
```
HttpBuilder.configure({ HttpObjectConfig t->
  ...
} as Consumer).get ...
```
