### ISSUE TITLE
Continuous integration build

### ISSUE THREAD

**Issue by cjstehno** [http-builder-ng/http-builder-ng#28]
It would be nice to have a http://drone.io or Travis build setup to fire when we update master or development. 

I can't set this up since I don't have permissions to add webhooks to the project.

Drone is free and easy to setup with your GitHub account.

**Comment by cjstehno** [comment]
Looks like I might have permissions to do this now - I will give it a try over the long weekend.

**Comment by cjstehno** [comment]
I have setup Travis-CI build for the project - after replacing the mock server library with another more stable one, it is passing; moving on to coverage reporting before merging this into `master`.

**Comment by cjstehno** [comment]
...and not so much. Travis and Gradle don't seem to get along. Have to work more on this later. Maybe try `--no-daemon`

**Comment by cjstehno** [comment]
I keep getting Gradle related exceptions during the test task execution:

```
Could not stop org.gradle.internal.actor.internal.DefaultActorFactory$NonBlockingActor@b274834.
org.gradle.internal.dispatch.DispatchException: Could not dispatch message [MethodInvocation method: processTestClass(org.gradle.api.internal.tasks.testing.DefaultTestClassRunInfo@1d3a0ea4)].
	at org.gradle.internal.dispatch.ExceptionTrackingFailureHandler.dispatchFailed(ExceptionTrackingFailureHandler.java:34)
	at org.gradle.internal.dispatch.FailureHandlingDispatch.dispatch(FailureHandlingDispatch.java:31)
	at org.gradle.internal.dispatch.AsyncDispatch.dispatchMessages(AsyncDispatch.java:132)
	at org.gradle.internal.dispatch.AsyncDispatch.access$000(AsyncDispatch.java:33)
	at org.gradle.internal.dispatch.AsyncDispatch$1.run(AsyncDispatch.java:72)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.gradle.process.internal.ExecException: Process 'Gradle Test Executor 7' finished with non-zero exit value 137
	at org.gradle.process.internal.DefaultExecHandle$ExecResultImpl.assertNormalExitValue(DefaultExecHandle.java:369)
	at org.gradle.process.internal.worker.DefaultWorkerProcess.waitForStop(DefaultWorkerProcess.java:165)
	at org.gradle.api.internal.tasks.testing.worker.ForkingTestClassProcessor.stop(ForkingTestClassProcessor.java:120)
	at org.gradle.api.internal.tasks.testing.processors.RestartEveryNTestClassProcessor.endBatch(RestartEveryNTestClassProcessor.java:63)
	at org.gradle.api.internal.tasks.testing.processors.RestartEveryNTestClassProcessor.processTestClass(RestartEveryNTestClassProcessor.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.FailureHandlingDispatch.dispatch(FailureHandlingDispatch.java:29)
	... 8 more
:test FAILED
```
Some Google searching suggested that it's memory, but our build should be well within normal JVM memory settings. I also saw it related to leaks in Netty, which lead me to replace the mock-server library with a more stable one - this worked for one build and now it fails again. I guess I will try one more round of test isolation and then shelve this if I can't get it working.

**Comment by cjstehno** [comment]
Got it working (with travis and coveralls). The issue was related to unexpected cookies and other errors being obscured by the forked tests.
