### ISSUE TITLE
nttp-builder-ng-core should have explicit dependency on commons-lang3

### ISSUE THREAD

**Issue by kgeis** [http-builder-ng/http-builder-ng#86]
commons-lang3's BooleanUtils is explicitly called in HttpObjectConfigImpl, but it is not referenced as a project dependency.

When I run a simple script to test http-builder-ng, I get this:

    Caught: java.lang.NoClassDefFoundError: org/apache/commons/lang3/BooleanUtils
    java.lang.NoClassDefFoundError: org/apache/commons/lang3/BooleanUtils
    	at groovyx.net.http.HttpObjectConfigImpl$Exec.<init>(HttpObjectConfigImpl.java:61)
    	at groovyx.net.http.HttpObjectConfigImpl.<init>(HttpObjectConfigImpl.java:41)
    	at groovyx.net.http.HttpBuilder.configure(HttpBuilder.java:161)
    	at groovyx.net.http.HttpBuilder.configure(HttpBuilder.java:137)
    	at groovyx.net.http.HttpBuilder$configure.call(Unknown Source)
    	at test.run(test.groovy:7)
    Caused by: java.lang.ClassNotFoundException: org.apache.commons.lang3.BooleanUtils
    	... 6 more

When I add

    @Grab('org.apache.commons:commons-lang3:3.5')

to my script, the error goes away.

**Comment by cjstehno** [comment]
This is a known issue and has been addressed in a pending release pull request. See #83.

**Comment by kgeis** [comment]
Thank you for the information. Sorry for the noise!

**Comment by cjstehno** [comment]
No problem. Thanks for letting us know.
